### ISSUE TITLE
help

### ISSUE THREAD

**Issue by ghost** [learn-co-curriculum/bash-navigation-osx#8]
Nothing has worked properly since i have started using this website. I really wanted to start learning coding but from one mess to another it seems. And now this help staff don't want to help which i can't blame them because of how much i have to keep talking to them. Hasn't gave me much faith towards coding unfortunately :/

**Comment by matbalez-zz** [comment]
I'm sorry you haven't had a great experience with Learn Carl. I hope you keep at it.

**Comment by ghost** [comment]
Hey mat yes I definitely will. It didn't start off well which was down to both sides, gradually getting the hang off it. Just got bit disappointed as I learnt a bit of html before I found this and found it easy but obviously learn are teaching me from scratch to learn it all.anyways I will stick at it :-) thanks for your support
