### ISSUE TITLE
Subl command doesn't work without some "fiddling"

### ISSUE THREAD

**Issue by marsikeda** [learn-co-curriculum/bash-navigation-osx#9]
I wasn't able to run subl . without getting the error message "-bash: subl: command not found" 
Some Googling led me to [this article by Olivier Lacan](http://olivierlacan.com/posts/launch-sublime-text-3-from-the-command-line/) which walked me step by step through what to do to get subl . to work. Should probably change the instruction or add a note/link for beginners.

**Comment by pletcher** [comment]
Thanks for opening this issue!

Keep in mind that this space is for specific issues related to the content of this lesson.

If you're reporting on the content of this lesson, it'd be super helpful if you could include a stack trace of any errors that you're seeing.

If you'd like to report a bug about the Learn IDE, the Ask a Question form, opening a file, or the lights not working on Learn, please report a bug directly on https://learn.co. (You can find the bug report form by clicking on your avatar in the upper right, and then selecting "Report A Bug".)

Please be sure to include steps to reproduce (be as detailed as possible) and any relevant information about your environment. (Are you using the Learn IDE? Coding on a refurbished toaster?) We'll be sure to figure out what's going on — and to jump in and help — just as soon as we can. Thanks!
